version: '3.8'

services:
  web-host-ui:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - phunparty-network

  # Add backend when ready
  # phunparty-backend:
  #   build:
  #     context: ./phunparty-backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@db:5432/phunparty
  #   depends_on:
  #     - db
  #   networks:
  #     - phunparty-network

  # # Database
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: phunparty
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - phunparty-network

networks:
  phunparty-network:
    driver: bridge

# volumes:
#   postgres_data:
