name: Deploy Web Host UI

on:
  push:
    branches: [ main ]
    paths: [ 'web-host-ui/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'web-host-ui/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'web-host-ui/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd web-host-ui
        npm ci
    
    - name: Run tests
      run: |
        cd web-host-ui
        npm test -- --coverage --watchAll=false
    
    - name: Build application
      run: |
        cd web-host-ui
        npm run build
    
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './web-host-ui/build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
    
    # Alternative deployment to Vercel (uncomment if preferred)
    # - name: Deploy to Vercel
    #   uses: amondnet/vercel-action@v25
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJECT_ID }}
    #     working-directory: ./web-host-ui
