name: Deploy FastAPI to Linode

on:
  push:
    branches: [main]
    paths:
      - "PhunParty/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

concurrency:
  group: deploy-phun-api
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      TARGET_DIR: ${{ secrets.TARGET_DIR }}
      PYTHON: ${{ secrets.PYTHON }}
      PIP: ${{ secrets.PIP }}

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # trust host key
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Rsync code to server
        run: |
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            PhunParty/ "$SSH_USER@$SSH_HOST:$TARGET_DIR/"

      - name: Install backend deps on server
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" bash -lc '
            set -e
            cd "$TARGET_DIR"
            # ensure venv exists (idempotent)
            [ -x .venv/bin/python ] || python3 -m venv .venv
            . .venv/bin/activate
            if [ -f phunparty-backend/requirements.txt ]; then
              pip install --upgrade pip wheel
              pip install -r phunparty-backend/requirements.txt
            fi
          '

      - name: Run Alembic (if present)
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" bash -lc '
            set -e
            cd "$TARGET_DIR"
            . .venv/bin/activate
            if [ -f phunparty-backend/alembic.ini ]; then
              cd phunparty-backend
              alembic upgrade head
            fi
          '

      - name: Restart systemd service
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" bash -lc '
            sudo systemctl restart phun-api
            sudo systemctl is-active phun-api
          '
