name: Deploy to Production

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Linode Deploy
              uses: appleboy/ssh-action@v0.1.9
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script_stop: true
                  script: |
                      set -euo pipefail
                      TARGET_DIR=/home/jay/apps/phun-api/PhunParty
                      BRANCH=main

                      # Ensure repo present and up-to-date
                      if [ -d "$TARGET_DIR/.git" ]; then
                        cd "$TARGET_DIR"
                        git fetch --prune --tags
                        git checkout "$BRANCH"
                        git reset --hard "origin/$BRANCH"
                      else
                        mkdir -p "$TARGET_DIR"
                        git clone --depth=1 -b "$BRANCH" "git@github.com:${{ github.repository }}.git" "$TARGET_DIR"
                        cd "$TARGET_DIR"
                      fi

                      # Python deps in venv
                      [ -x .venv/bin/python ] || python3 -m venv .venv
                      . .venv/bin/activate
                      if [ -f phunparty-backend/requirements.txt ]; then
                        pip install --upgrade pip wheel
                        pip install -r phunparty-backend/requirements.txt
                      fi

                      # Optional: run DB migrations if you use Alembic
                      if [ -f phunparty-backend/alembic.ini ]; then
                        cd phunparty-backend
                        alembic upgrade head
                        cd ..
                      fi

                      # Restart FastAPI service
                      sudo systemctl restart phun-api
                      sudo systemctl is-active phun-api
